server:
  port : 8080
spring :
  profiles :
    active : develop

profile :
    profile-yml-main

yml-config : yml, config

---
spring :
  profiles : develop

server :
  port : 8888
---

---
spring :
  profiles : release

server :
  port : 80
---